# Generated by Django 4.1.7 on 2023-04-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_rename_author_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
